### ISSUE TITLE
HTTP Error?

### ISSUE THREAD

**Issue by deve2ev** [talaexe/Spotify-RFID-Record-Player#2]
I have followed all steps and authorized spotify, but then when I execute `spotifyTest.py`, i get this:

`HTTP Error for PUT to https://api.spotify.com/v1/me/player with Params: {} returned 404 due to Not found.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/spotipy/client.py", line 245, in _internal_call
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/me/player
`

Executing `player.py` and scanning a tag returns the following:

``HTTP Error for PUT to https://api.spotify.com/v1/me/player with Params: {} returned 404 due to Not found.
http status: 404, code:-1 - https://api.spotify.com/v1/me/player:
 Not found., reason: None``

**Comment by jlpz-dev** [comment]
Without looking too deep into this, the reason you're getting this is because your API call is invalid and the request did not reach anything. Its the same as going to a website that is no longer active or was removed. I would check that you are using the proper API call as sometimes guides use some calls that get updated with new endpoints or they require specific parameters to your situation.
